import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import url from "node:url";

interface JournalEntry {
	breakpoints?: boolean;
	idx: number;
	tag: string;
	version?: string;
	when: number;
}

interface Journal {
	dialect?: string;
	entries: JournalEntry[];
	version?: string;
}

interface ClientMigration {
	bps: boolean;
	folderMillis: number;
	hash: string;
	sql: string[];
	tag: string;
}

const STATEMENT_BREAKPOINT = "--> statement-breakpoint";

const rootDir = path.resolve(url.fileURLToPath(new URL("..", import.meta.url)));
const drizzleDir = path.join(rootDir, "drizzle");
const journalPath = path.join(drizzleDir, "meta", "_journal.json");

const outDir = path.join(rootDir, "src", "db", "migrations", "client");
const outFile = path.join(outDir, "index.ts");

function readJsonFile(filePath: string): unknown {
	if (!fs.existsSync(filePath)) {
		throw new Error(`Missing file: ${filePath}`);
	}

	const raw = fs.readFileSync(filePath, "utf8");
	return JSON.parse(raw) as unknown;
}

function sha256Hex(input: string): string {
	return crypto.createHash("sha256").update(input).digest("hex");
}

function splitSqlStatements(rawSql: string): string[] {
	return rawSql
		.split(STATEMENT_BREAKPOINT)
		.map((stmt) => stmt.trim())
		.filter((stmt) => stmt.length > 0);
}

function assertJournal(value: unknown): Journal {
	if (typeof value !== "object" || value === null) {
		throw new TypeError("Invalid journal JSON: expected object");
	}

	const record = value as Record<string, unknown>;
	const entries = record.entries;

	if (!Array.isArray(entries)) {
		throw new TypeError("Invalid journal JSON: expected entries[]");
	}

	return record as unknown as Journal;
}

function buildClientMigrations(journal: Journal): ClientMigration[] {
	const sorted = [...journal.entries].sort((a, b) => a.idx - b.idx);

	return sorted.map((entry) => {
		const migrationPath = path.join(drizzleDir, `${entry.tag}.sql`);
		if (!fs.existsSync(migrationPath)) {
			throw new Error(`Missing migration file: ${migrationPath}`);
		}

		const rawSql = fs.readFileSync(migrationPath, "utf8");

		return {
			tag: entry.tag,
			folderMillis: Number(entry.when),
			bps: Boolean(entry.breakpoints),
			hash: sha256Hex(rawSql),
			sql: splitSqlStatements(rawSql),
		};
	});
}

function formatGeneratedModule(params: {
	migrations: ClientMigration[];
	dialect: string;
	journalVersion: string;
}): string {
	const { migrations, dialect, journalVersion } = params;

	const migrationsJson = JSON.stringify(migrations, null, 2);
	const metaJson = JSON.stringify(
		{
			dialect,
			journalVersion,
		},
		null,
		2
	);

	return [
		"/*",
		" * This file is generated by scripts/build-client-migrations.ts.",
		" * Do not edit it by hand.",
		" */",
		"",
		"export interface ClientMigration {",
		"\tbps: boolean;",
		"\tfolderMillis: number;",
		"\thash: string;",
		"\tsql: string[];",
		"\ttag: string;",
		"}",
		"",
		`export const clientMigrations: ClientMigration[] = ${migrationsJson};`,
		"",
		`export const clientMigrationsMeta = ${metaJson} as const;`,
		"",
	].join("\n");
}

function main(): void {
	const journalRaw = readJsonFile(journalPath);
	const journal = assertJournal(journalRaw);
	const migrations = buildClientMigrations(journal);

	const dialect =
		typeof journal.dialect === "string" ? journal.dialect : "sqlite";
	const journalVersion =
		typeof journal.version === "string" ? journal.version : "unknown";

	fs.mkdirSync(outDir, { recursive: true });
	const moduleText = formatGeneratedModule({
		migrations,
		dialect,
		journalVersion,
	});
	fs.writeFileSync(outFile, moduleText, "utf8");

	process.stdout.write(
		`Generated client migrations module: ${path.relative(rootDir, outFile)}\n`
	);
}

main();
