/*
 * This file is generated by scripts/build-client-migrations.ts.
 * Do not edit it by hand.
 */

export interface ClientMigration {
	bps: boolean;
	folderMillis: number;
	hash: string;
	sql: string[];
	tag: string;
}

export const clientMigrations: ClientMigration[] = [
	{
		tag: "0000_todo-and-users-schema",
		folderMillis: 1775092889100,
		bps: true,
		hash: "da1528075d066e9c748098d408835d02ca3c4799a373d724607709d5ba23117d",
		sql: [
			"CREATE TABLE `todos_table` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`title` text NOT NULL,\n\t`description` text,\n\t`completed` integer DEFAULT 0 NOT NULL,\n\t`createdAt` real DEFAULT 1775092889094 NOT NULL\n);",
			"CREATE TABLE `users_table` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text NOT NULL,\n\t`age` integer NOT NULL,\n\t`email` text NOT NULL\n);",
			"CREATE UNIQUE INDEX `users_table_email_unique` ON `users_table` (`email`);",
		],
	},
];

export const clientMigrationsMeta = {
	dialect: "sqlite",
	journalVersion: "7",
} as const;
